[workspace]
resolver = "2"

members = [
    "ui",
    "model",
    "engine",
    "benchmark",
    "lichess_bot"
]

[profile.release]
lto = true

[workspace.dependencies]
model = {path = "./model"}
engine = {path = "./engine"}

