[package]
name = "lichess_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
model = {workspace = true}
engine = {workspace = true}
vampirc-uci = "0.11"
chrono = "0.4.39"

[[bin]]
name = "lichess_bot"
path = "src/main.rs"
